using System.Windows;
using System.Windows.Media;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MapleGuardian.Models;
using MapleGuardian.Services;
using Application = System.Windows.Application;
using Brush = System.Windows.Media.Brush;
using Brushes = System.Windows.Media.Brushes;
using Color = System.Windows.Media.Color;
using Timer = System.Threading.Timer;
using Directory = System.IO.Directory;

namespace MapleGuardian.ViewModels;

/// <summary>
/// Main ViewModel for the dashboard.
/// Orchestrates all services and exposes bindable properties.
/// This is the "brain" of the application — coordinates VPN monitoring,
/// firewall management, reconnection, and UI state.
/// </summary>
public partial class MainViewModel : ObservableObject, IDisposable
{
    // Services
    private readonly AppConfig _config;
    private readonly LogService _logService;
    private readonly VpnMonitorService _vpnMonitor;
    private readonly FirewallService _firewallService;
    private readonly SoftEtherService _softEtherService;
    private readonly NetworkCheckerService _networkChecker;
    private readonly NotificationService _notificationService;
    private readonly StartupManager _startupManager;
    private readonly ProcessMonitorService _processMonitor;
    private readonly UpdateService _updateService;
    private bool _disposed;

    // ═══════════════════════════════════════════════════════
    // Observable Properties (auto-generated by source generator)
    // ═══════════════════════════════════════════════════════

    [ObservableProperty] private string _vpnStatusText = "Checking...";
    [ObservableProperty] private Brush _vpnStatusColor = Brushes.Gray;
    [ObservableProperty] private string _vpnStatusIcon = "⏳";
    [ObservableProperty] private bool _isVpnConnected;

    [ObservableProperty] private string _serverLocation = "Detecting...";
    [ObservableProperty] private string _publicIp = "Checking...";
    [ObservableProperty] private string _ipTypeText = "Checking...";
    [ObservableProperty] private Brush _ipTypeColor = Brushes.Gray;
    [ObservableProperty] private string _ipTypeIcon = "🔍";
    [ObservableProperty] private bool _isDatacenterWarning;
    [ObservableProperty] private string _pingText = "-- ms";
    [ObservableProperty] private Brush _pingColor = Brushes.Gray;

    [ObservableProperty] private string _dnsStatusText = "Checking...";
    [ObservableProperty] private Brush _dnsStatusColor = Brushes.Gray;
    [ObservableProperty] private string _dnsStatusIcon = "⏳";

    [ObservableProperty] private string _firewallStatusText = "OFF";
    [ObservableProperty] private Brush _firewallStatusColor = Brushes.Gray;
    [ObservableProperty] private string _firewallStatusIcon = "⬛";

    [ObservableProperty] private string _gameStatusText = "STOPPED";
    [ObservableProperty] private Brush _gameStatusColor = Brushes.Gray;
    [ObservableProperty] private string _gameStatusIcon = "⏹";

    [ObservableProperty] private bool _isReconnecting;
    [ObservableProperty] private string _statusBarText = "Starting...";
    [ObservableProperty] private Brush _statusBarColor = Brushes.Gray;

    [ObservableProperty] private bool _startWithWindows;
    [ObservableProperty] private string _uptimeText = "0:00:00";

    private DateTime _startTime;
    private Timer? _uptimeTimer;

    // ═══════════════════════════════════════════════════════
    // Constructor
    // ═══════════════════════════════════════════════════════

    public MainViewModel(AppConfig config)
    {
        _config = config;
        _startTime = DateTime.Now;

        // Initialize services
        _logService = new LogService(config);
        _vpnMonitor = new VpnMonitorService(config, _logService);
        _firewallService = new FirewallService(config, _logService);
        _softEtherService = new SoftEtherService(config, _logService);
        _networkChecker = new NetworkCheckerService(config, _logService);
        _notificationService = new NotificationService(_logService);
        _startupManager = new StartupManager(_logService);
        _processMonitor = new ProcessMonitorService(config, _logService);
        _updateService = new UpdateService(config, _logService);

        // Wire up events
        _vpnMonitor.StatusChanged += OnVpnStatusChanged;
        _networkChecker.ResultsUpdated += OnNetworkResultsUpdated;
        _processMonitor.StatusChanged += OnGameStatusChanged;
        _softEtherService.ReconnectStarted += (_, _) => IsReconnecting = true;
        _softEtherService.ReconnectCompleted += OnReconnectCompleted;
        _updateService.UpdateAvailable += OnUpdateAvailable;

        // Load settings
        StartWithWindows = _startupManager.IsRegistered();

        // Uptime timer
        _uptimeTimer = new Timer(_ => UpdateUptime(), null, TimeSpan.Zero, TimeSpan.FromSeconds(1));
    }

    // ═══════════════════════════════════════════════════════
    // Initialization
    // ═══════════════════════════════════════════════════════

    /// <summary>
    /// Start all services. Called after UI is loaded.
    /// </summary>
    public async void StartAllServices()
    {
        _logService.Info("App", "🍁 Maple Guardian V2 starting...");

        // Check initial firewall state
        _firewallService.CheckRulesStatus();
        UpdateFirewallDisplay();

        // Start monitoring
        _vpnMonitor.Start();
        _networkChecker.Start();
        _processMonitor.Start();

        StatusBarText = "Monitoring active";
        StatusBarColor = new SolidColorBrush(Color.FromRgb(63, 185, 80)); // Green

        _logService.Info("App", "All services started");

        // Check for updates asynchronously
        await _updateService.CheckForUpdatesAsync();
    }

    private void OnUpdateAvailable(object? sender, UpdateInfo updateInfo)
    {
        Application.Current?.Dispatcher.Invoke(() =>
        {
            _notificationService.NotifyInfo(
                "🎉 New Update Available!",
                $"Maple Guardian v{updateInfo.Version} is available. Opening update...");
            StatusBarText = $"🎉 New update v{updateInfo.Version} available!";
        });
    }

    // ═══════════════════════════════════════════════════════
    // Event Handlers
    // ═══════════════════════════════════════════════════════

    private void OnVpnStatusChanged(object? sender, VpnStatusChangedEventArgs e)
    {
        Application.Current?.Dispatcher.Invoke(() =>
        {
            UpdateVpnDisplay(e.NewStatus);

            switch (e.NewStatus)
            {
                case VpnStatus.Connected:
                    HandleVpnConnected();
                    break;
                case VpnStatus.Disconnected:
                    HandleVpnDisconnected();
                    break;
            }
        });
    }

    private void HandleVpnConnected()
    {
        _logService.Info("Guardian", "✅ VPN connected — flushing DNS and disabling firewall rules");

        // Flush DNS Cache to prevent DNS Leak
        _networkChecker.FlushDnsCache();

        // Disable firewall rules (allow game traffic)
        _firewallService.DisableRules();
        UpdateFirewallDisplay();

        // Clear blocked game status
        _processMonitor.ClearBlocked();

        // Notify if was previously disconnected
        if (IsReconnecting)
        {
            _notificationService.NotifyVpnReconnected();
        }

        StatusBarText = "VPN connected — monitoring active";
        StatusBarColor = new SolidColorBrush(Color.FromRgb(63, 185, 80));
    }

    private async void HandleVpnDisconnected()
    {
        _logService.Warning("Guardian", "🔴 VPN LOST — instant lockdown! Enabling firewall rules & flushing DNS");

        // Enable firewall rules immediately (block game traffic)
        _firewallService.EnableRules();
        UpdateFirewallDisplay();

        // Flush DNS Cache immediately to avoid query leaks
        _networkChecker.FlushDnsCache();

        // Mark game as blocked
        _processMonitor.SetBlocked();

        // Send notification
        _notificationService.NotifyVpnLost();

        StatusBarText = "⚠️ VPN LOST — reconnecting...";
        StatusBarColor = new SolidColorBrush(Color.FromRgb(248, 81, 73)); // Red

        // Attempt reconnection
        _vpnMonitor.SetReconnecting();
        var success = await _softEtherService.ReconnectAsync();

        if (!success && !_disposed)
        {
            _notificationService.NotifyReconnectFailed();
            StatusBarText = "❌ Reconnection failed";
        }
    }

    private void OnReconnectCompleted(object? sender, bool success)
    {
        Application.Current?.Dispatcher.Invoke(() =>
        {
            IsReconnecting = false;
            if (success)
            {
                StatusBarText = "VPN reconnected — monitoring active";
                StatusBarColor = new SolidColorBrush(Color.FromRgb(63, 185, 80));
            }
            else
            {
                StatusBarText = "❌ Reconnection failed";
                StatusBarColor = new SolidColorBrush(Color.FromRgb(248, 81, 73));
                _vpnMonitor.SetDisconnected();
            }
        });
    }

    private void OnNetworkResultsUpdated(object? sender, EventArgs e)
    {
        Application.Current?.Dispatcher.Invoke(() =>
        {
            // Update IP & Location
            PublicIp = _networkChecker.PublicIp;
            ServerLocation = _networkChecker.ServerLocation;

            // Update IP Type (Residential vs Datacenter/IDC)
            IpTypeText = _networkChecker.IpType;
            IsDatacenterWarning = _networkChecker.IsDatacenterIp;
            if (_networkChecker.IsDatacenterIp)
            {
                IpTypeIcon = "⚠️";
                IpTypeColor = new SolidColorBrush(Color.FromRgb(248, 81, 73)); // Red alert
            }
            else if (_networkChecker.IpType == "Residential ISP")
            {
                IpTypeIcon = "🏡";
                IpTypeColor = new SolidColorBrush(Color.FromRgb(63, 185, 80)); // Safe green
            }
            else
            {
                IpTypeIcon = "🔍";
                IpTypeColor = Brushes.Gray;
            }

            // Update Ping
            if (_networkChecker.PingMs >= 0)
            {
                PingText = $"{_networkChecker.PingMs} ms";
                PingColor = _networkChecker.PingMs switch
                {
                    < 50 => new SolidColorBrush(Color.FromRgb(63, 185, 80)),   // Green
                    < 100 => new SolidColorBrush(Color.FromRgb(210, 153, 34)), // Orange
                    _ => new SolidColorBrush(Color.FromRgb(248, 81, 73))       // Red
                };
            }
            else
            {
                PingText = "Timeout";
                PingColor = new SolidColorBrush(Color.FromRgb(248, 81, 73));
            }

            // Update DNS
            UpdateDnsDisplay(_networkChecker.DnsStatus);
        });
    }

    private void OnGameStatusChanged(object? sender, GameStatus status)
    {
        Application.Current?.Dispatcher.Invoke(() => UpdateGameDisplay(status));
    }

    // ═══════════════════════════════════════════════════════
    // Display Update Methods
    // ═══════════════════════════════════════════════════════

    private void UpdateVpnDisplay(VpnStatus status)
    {
        switch (status)
        {
            case VpnStatus.Connected:
                VpnStatusText = "Connected";
                VpnStatusIcon = "🟢";
                VpnStatusColor = new SolidColorBrush(Color.FromRgb(63, 185, 80));
                IsVpnConnected = true;
                break;
            case VpnStatus.Disconnected:
                VpnStatusText = "LOST";
                VpnStatusIcon = "🔴";
                VpnStatusColor = new SolidColorBrush(Color.FromRgb(248, 81, 73));
                IsVpnConnected = false;
                break;
            case VpnStatus.Reconnecting:
                VpnStatusText = "Reconnecting...";
                VpnStatusIcon = "🟡";
                VpnStatusColor = new SolidColorBrush(Color.FromRgb(210, 153, 34));
                IsVpnConnected = false;
                break;
            default:
                VpnStatusText = "Unknown";
                VpnStatusIcon = "⚪";
                VpnStatusColor = Brushes.Gray;
                IsVpnConnected = false;
                break;
        }
    }

    private void UpdateFirewallDisplay()
    {
        switch (_firewallService.CurrentStatus)
        {
            case FirewallStatus.Enabled:
                FirewallStatusText = "ENABLED";
                FirewallStatusIcon = "🟥";
                FirewallStatusColor = new SolidColorBrush(Color.FromRgb(248, 81, 73));
                break;
            case FirewallStatus.Disabled:
                FirewallStatusText = "OFF";
                FirewallStatusIcon = "⬛";
                FirewallStatusColor = new SolidColorBrush(Color.FromRgb(139, 148, 158));
                break;
            case FirewallStatus.Error:
                FirewallStatusText = "ERROR";
                FirewallStatusIcon = "⚠️";
                FirewallStatusColor = new SolidColorBrush(Color.FromRgb(210, 153, 34));
                break;
        }
    }

    private void UpdateDnsDisplay(DnsStatus status)
    {
        switch (status)
        {
            case DnsStatus.Safe:
                DnsStatusText = "SAFE";
                DnsStatusIcon = "✅";
                DnsStatusColor = new SolidColorBrush(Color.FromRgb(63, 185, 80));
                break;
            case DnsStatus.Leaked:
                DnsStatusText = "LEAKED";
                DnsStatusIcon = "⚠️";
                DnsStatusColor = new SolidColorBrush(Color.FromRgb(248, 81, 73));
                break;
            default:
                DnsStatusText = "Unknown";
                DnsStatusIcon = "⏳";
                DnsStatusColor = Brushes.Gray;
                break;
        }
    }

    private void UpdateGameDisplay(GameStatus status)
    {
        switch (status)
        {
            case GameStatus.Running:
                GameStatusText = "RUNNING";
                GameStatusIcon = "🎮";
                GameStatusColor = new SolidColorBrush(Color.FromRgb(63, 185, 80));
                break;
            case GameStatus.Stopped:
                GameStatusText = "STOPPED";
                GameStatusIcon = "⏹";
                GameStatusColor = new SolidColorBrush(Color.FromRgb(139, 148, 158));
                break;
            case GameStatus.Blocked:
                GameStatusText = "BLOCKED";
                GameStatusIcon = "🚫";
                GameStatusColor = new SolidColorBrush(Color.FromRgb(248, 81, 73));
                break;
        }
    }

    private void UpdateUptime()
    {
        var elapsed = DateTime.Now - _startTime;
        Application.Current?.Dispatcher.Invoke(() =>
        {
            UptimeText = elapsed.ToString(@"h\:mm\:ss");
        });
    }

    // ═══════════════════════════════════════════════════════
    // Commands
    // ═══════════════════════════════════════════════════════

    [RelayCommand]
    public async Task ReconnectVpn()
    {
        if (_softEtherService.IsReconnecting)
        {
            _softEtherService.CancelReconnect();
            return;
        }

        _logService.Info("User", "Manual reconnect requested");
        StatusBarText = "🔄 Reconnecting VPN...";
        _vpnMonitor.SetReconnecting();
        await _softEtherService.ReconnectAsync();
    }

    [RelayCommand]
    private void OpenLogs()
    {
        try
        {
            var logDir = _logService.GetLogDirectory();
            if (Directory.Exists(logDir))
            {
                System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                {
                    FileName = logDir,
                    UseShellExecute = true
                });
            }
        }
        catch (Exception ex)
        {
            _logService.Error("User", "Failed to open logs folder", ex);
        }
    }

    [RelayCommand]
    private void ToggleStartup()
    {
        _startupManager.Toggle();
        StartWithWindows = _startupManager.IsRegistered();
        _logService.Info("User", $"Startup with Windows: {StartWithWindows}");
    }

    [RelayCommand]
    private void ExitApp()
    {
        _logService.Info("App", "Exit requested by user");
        Dispose();
        Application.Current?.Shutdown();
    }

    // ═══════════════════════════════════════════════════════
    // Tray Icon Helpers
    // ═══════════════════════════════════════════════════════

    /// <summary>Get current tray tooltip text</summary>
    public string GetTrayToolTip()
    {
        return $"Maple Guardian — VPN: {VpnStatusText} | Ping: {PingText}";
    }

    // ═══════════════════════════════════════════════════════
    // Cleanup
    // ═══════════════════════════════════════════════════════

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;

        _uptimeTimer?.Dispose();
        _vpnMonitor.Dispose();
        _networkChecker.Dispose();
        _processMonitor.Dispose();
        _logService.Info("App", "Maple Guardian stopped");
        _logService.Dispose();
        NotificationService.ClearAll();

        GC.SuppressFinalize(this);
    }
}
